### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by kate187** [Fumblessi/ot-harjoitustyo#1]
Release Viikko5 ladattu 11:15 9.12.19

Kommentteja:

[-] Background ja ProficiencyList käsittelevät molemmat hahmon skillejä ja ne ovat silti eriytetty omiksi luokikseen. Tämä on vastoin DRY-periaatetta. Backgroundin ja ProficiencyListin voisi yhdistää mielekkäämmällä tavalla siten, että esimerkiksi hahmon skillit ovat lueteltu yhdessä paikassa ja alkiohin itseensä on merkitty muuttujalla ovatko ne osana jotain muuta kokonaisuutta kuten Backgroundia tässä tapauksessa.

[-] ProficiencyListin addProf metodi on hieman epäselvä muuttujanimen “skill” vuoksi rivillä 36. Muuttujanimi tulisi olla geneerisempi tässä tilanteessa.

[+] Koodin kirjoitusasu vastaa camelCasea ja koodi on kirjoitettu englanniksi

[+] Ohjelmalogiikan metodit ovat sopivan pituisia. Single Responsiblity on pidetty mielessä.

[+] Hahmon attribuuttiluokkien tietokantaoperaatioita on abstrahoitu dao-mallia käyttäen, mikä on kätevä ja selkeä tapa toteuttaa tietokantatoiminnallisuutta.

[-] Tässä julkaisussa tietokannalla ei ole paljoa käyttäarvoa itse käyttäjälle. Miten käyttäjä voi hakea tallentamiaan hahmoattribuutteja, tai miksi niitä kuuluisi tallentaa?

[-] Testit voisivat olla parempia. SettingsTest.java testaa gettereiden ja settereiden toiminnallisuutta, mikä ei ole yksinään mielekäs testin aihe.

**Comment by Fumblessi** [comment]
Kiitos hyvästä palautteesta!

- Poistin ProficiencyListin kokonaan (se oli muutenkin hieman luonnosluokka vielä, täytyy ehkä vasta tarkemmin miettiä miten generointitoiminallisuus hajautetaan, kun pääsen siihen asti. Sen idea oli lähinnä vähentää Generator-luokan taakkaa, sillä siitä on tulossa tällä hetkellä aivan liian pitkä Checkstyle-suositukset huomioon ottaen).

- Tietokantaa on päivitetty viimeisestä, nyt siellä on enemmänkin toiminnallisuutta kuin vain lisääminen. Idea miksi tietokantaan pitää käyttäjän pystyä vaikuttamaan, liittyy generaattorin pitkäikäisyyteen - kun pelit säännöt muuttuu tai tulee lisää mahdollisia pelattavia rotuja tai luokka tai niiden hallitsemia taitoja, voi käyttäjä nyt lisätä niitä sitä mukaa generaattoriin ja se pysyy edelleen toiminnallisena.

- Testejä rakennettu mittavasti enemmän.
